# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
assistant_id: FIPU_bot
language: hr

pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    token_pattern: (?u)\b\w+\b
  - name: DucklingEntityExtractor
    url: http://localhost:8000
    dimensions:
      - number
  - name: DIETClassifier
    epochs: 150
    constrain_similarities: True
  - name: EntitySynonymMapper

policies:
  - name: TEDPolicy
    epochs: 100
  - name: AugmentedMemoizationPolicy
  - name: RulePolicy
